[versions]
kotlin_version = "2.0.21"
ksp_version = "2.0.21-1.0.28"
hilt_version = "2.51.1"
gradleplugin = "8.7.3"
detekt_version = "1.23.5"
kover_version = "0.9.0"
ktlint_version = "12.1.0"
activity-compose = "1.9.3"
compose-bom = "2024.12.01"
androidx-junit = "1.2.1"
appcompat = "1.7.0"
coil-compose = "2.5.0"
glide = "1.0.0-beta01"
core-ktx = "1.15.0"
core-testing = "2.2.0"
espresso-core = "3.6.1"
hilt-android = "2.51.1"
junit = "4.13.2"
kotlinx-coroutines-android = "1.8.1"
lifecycle-runtime-ktx = "2.8.7"
material = "1.12.0"
timber = "5.0.1"
truth = "1.4.2"
kotlin = "2.0.21"
arrow = "1.2.1"
annotation-jvm = "1.9.1"
jreleaser = "1.15.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
compose-glide = { module = "com.github.bumptech.glide:compose", version.ref = "glide" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-android" }
material = { module = "com.google.android.material:material", version.ref = "material" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotation-jvm" }

[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt_version" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover_version" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint_version" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }